### ISSUE TITLE
Mostly-valid conventional commit subject line not recognized

### ISSUE THREAD

**Issue by SKalt** [gbprod/tree-sitter-gitcommit#38]
Context: I'm writing a language server to provide completion and linting for conventional commits.  I'd like to be able to take the following commit message
```
type(scope)! subject goes here
```
and recover from the typo, a missing colon.  However, that commit message parses as 
```scm
(ERROR) ; if not followed by a newline, else
(source (subject)) ; if followed by a newline
```
I was expecting the parse tree to resemble
```scm
(source
  (subject
    (ERROR (type) (scope) "!" (message))))
```

This isn't a blocker for me, since I'm falling back onto a hand-written fault-tolerant parser for conventional commit subjects.

**Comment by gbprod** [comment]
Hey @SKalt 
I've design this parser to recognize conventionnal commit only if the `xxx(yyy):` sequence is complete, otherwise, the subject will be recognize as a simple git subject. So, this behavior is what I expect from this parser and seems to be the more convenient for most users.
It allows to be used seemlessly by users who doesn't use conventionnal commit.

Maybe it could be interesting to work on a gitcommit parser that only allows conventionnal commits ?

**Comment by SKalt** [comment]
> Maybe it could be interesting to work on a gitcommit parser that only allows conventional commits?

I would be interested! In order to write a parser for `.git/COMMIT_EDITMSG` that recognizes conventional commits, I'd start by splitting `tree-sitter-gitcommit` into two grammars: 
- a base grammar that parses any `.git/COMMIT_EDITMSG` file, no matter the commit format
- an [injected grammar](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection) to match conventional commit subjects

Would you be interested in a PR with that split? I'd also be happy to maintain a fork of this repo.
