### ISSUE TITLE
Message only overflows at 74

### ISSUE THREAD

**Issue by MithicSpirit** [gbprod/tree-sitter-gitcommit#67]
The usual conventions are that messages overflow at 73 (72 is the maximum), but this parser only has them overflowing at 74. I suspect that the issue is due to the regex for `SUMMARY` allowing up to 72 characters but still being preceded by `NOT_A_COMMENT`, which includes an additional character. Additionally, note that while the subject line overflows at 51, `SUBJECT` only allows for 49 characters (presumably because it also is preceded by a `NOT_A_COMMENT`).

Since these appear to be the only places that `NOT_A_COMMENT` is used, I believe that it would make sense to remove it altogether and include the `[^#]` directly in `SUMMARY` and `SUBJECT`. Alternatively, there may be a way to have it check whether a `#` is present without consuming it, although I'm not familiar enough with tree-sitter to know.

**Comment by gbprod** [comment]
Hello @MithicSpirit !
Thanks for your feedback.
However, since the latests discussions here : https://github.com/gbprod/tree-sitter-gitcommit/issues/46 and https://www.reddit.com/r/neovim/comments/1cm5zir/question_should_i_commit_summaries_not_following/ I pretty sure that's I'll remove this feature soon (I'll explain the reasons later and I will give another way to do that easily).
So, I think you're right, there probably an issue here but I will not fix it :sweat_smile:

**Comment by MithicSpirit** [comment]
Fair enough
