### ISSUE TITLE
List of languages supported by the parser

### ISSUE THREAD

**Issue by thatlittleboy** [gbprod/tree-sitter-gitcommit#9]
Given that this project's main selling point is the support for generic languages (non-English), I think it's worth a mention on the project `README.md`.\
I think we can do a list, similar to [`nvim-treesitter`](https://github.com/nvim-treesitter/nvim-treesitter/#supported-languages), (not programming languages but for languages "English", "Russian", "Chinese (Simplified)", etc..)

This way, users know at a glance whether their own language is supported by your parser or not.

**Comment by gbprod** [comment]
Hey, thanks for all the feedbacks !

I've not specified all supported languages because (I hope) it should support all languages supported by git.
However, I think it's a good idea to list supported languages.

You can find all language and translation from the git repository : https://github.com/git/git/tree/master/po
